# Generated by Django 4.0.7 on 2022-11-02 01:39

from django.db import migrations

def replace_composite_keys(apps, schema_editor):
    from django.db import connection, transaction

    tables = ('now_br', 'now_coll_meth', 'now_lr', 'now_ls', 'now_mus', 'now_plr', 'now_proj_people', 'now_psr', 'now_reg_coord_country', 'now_reg_coord_people',
        'now_sp_coord_people', 'now_sp_coord_taxa', 'now_sr', 'now_ss', 'now_strat_coord_people', 'now_tr', 'now_tur', 'ref_authors', 'ref_field_name', 'ref_keywords_ref')

    cursor = connection.cursor()

    for table in tables:
        sql = 'ALTER TABLE IF EXISTS {table} DROP PRIMARY KEY, ADD COLUMN `id` BIGINT (20) UNSIGNED PRIMARY KEY AUTO_INCREMENT;'.format(table=table)
        cursor.execute(sql)

    cursor.close()

class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(replace_composite_keys),
    ]
