# Generated by Django 4.0.7 on 2022-10-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComMlist',
            new_name='ComMuseumList',
        ),
    ]
