# Generated by Django 4.0.7 on 2022-11-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nowbr',
            unique_together={('buid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowcollmeth',
            unique_together={('lid', 'coll_meth')},
        ),
        migrations.AlterUniqueTogether(
            name='nowlr',
            unique_together={('luid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowls',
            unique_together={('lid', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='nowmus',
            unique_together={('lid', 'museum')},
        ),
        migrations.AlterUniqueTogether(
            name='nowplr',
            unique_together={('lid', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojpeople',
            unique_together={('pid', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowpsr',
            unique_together={('pid', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordcountry',
            unique_together={('reg_coord', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordpeople',
            unique_together={('reg_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordpeople',
            unique_together={('sp_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordtaxa',
            unique_together={('sp_coord', 'order_name', 'family_name')},
        ),
        migrations.AlterUniqueTogether(
            name='nowsr',
            unique_together={('suid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowss',
            unique_together={('lid', 'sed_struct')},
        ),
        migrations.AlterUniqueTogether(
            name='nowstratcoordpeople',
            unique_together={('strat_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtr',
            unique_together={('tuid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtur',
            unique_together={('bid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='refauthors',
            unique_together={('rid', 'field_id', 'au_num')},
        ),
        migrations.AlterUniqueTogether(
            name='reffieldname',
            unique_together={('field_id', 'ref_type')},
        ),
        migrations.AlterUniqueTogether(
            name='refkeywordsref',
            unique_together={('keywords', 'rid')},
        ),
    ]
