# Generated by Django 4.0.7 on 2022-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0002_rename_commlist_commuseumlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowTuBound',
            new_name='NowTimeUnitBoundary',
        ),
    ]
