# Generated by Django 4.0.7 on 2022-10-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0004_rename_nowtusequence_nowtimeunitsequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowBau',
            new_name='NowTimeUnitBoundaryUpdate',
        ),
    ]
