# Generated by Django 4.0.7 on 2022-11-09 11:21

from django.db import migrations, models
import django.db.models.deletion
import hashlib

def fk_migration(table, fk_column, foreign_table, pk_column):
    # 1. Create temporary column
    # 2. insert foreign table id to temp column by matching fk value to former pk column value
    # 3. replace original foreign key column with the temporary column and drop the original

    temp_col = fk_column + '_' + hashlib.md5(fk_column.encode('utf8')).hexdigest()

    return '''
        ALTER TABLE `{table}` ADD {temp_col} BIGINT (20);
        UPDATE `{table}` SET {temp_col} = (SELECT id FROM {foreign_table} WHERE {foreign_table}.{pk_column} = {table}.{fk_column});
        ALTER TABLE `{table}` DROP COLUMN {fk_column};
        ALTER TABLE `{table}` RENAME COLUMN {temp_col} TO {fk_column};
        '''.format(table=table, fk_column=fk_column, foreign_table=foreign_table, pk_column=pk_column, temp_col=temp_col)

class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0004_rename_models'),
    ]

    operations = [

        ########################################
        # Drop all constraints
        ########################################

        migrations.AlterUniqueTogether(
            name='nowcollectingmethod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowlocalityspecies',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowlocalityupdatereference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowmuseum',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectlocality',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectpeople',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectspecies',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordcountry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordpeople',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowsedimentarystructure',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordpeople',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordtaxa',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowspeciesupdatereference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowstratcoordpeople',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitboundaryreference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitboundaryupdatereference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitupdatereference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='refauthors',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reffieldname',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='refkeywordsref',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nowcollectingmethod',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocality',
            name='bfa_max',
            field=models.ForeignKey(blank=True, db_column='bfa_max', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bfa_max', to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowlocality',
            name='bfa_min',
            field=models.ForeignKey(blank=True, db_column='bfa_min', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bfa_min', to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='species',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowlocalitysynonym',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lau_authorizer',
            field=models.ForeignKey(db_column='lau_authorizer', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lau_coordinator',
            field=models.ForeignKey(db_column='lau_coordinator', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='luid',
            field=models.ForeignKey(db_column='luid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocalityupdate'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowmuseum',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowmuseum',
            name='museum',
            field=models.ForeignKey(db_column='museum', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.commuseumlist'),
        ),
        migrations.AlterField(
            model_name='nowproject',
            name='contact',
            field=models.ForeignKey(db_column='contact', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowprojectlocality',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowprojectlocality',
            name='pid',
            field=models.ForeignKey(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='pid',
            field=models.ForeignKey(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectspecies',
            name='pid',
            field=models.ForeignKey(db_column='pid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectspecies',
            name='species',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowregcoordcountry',
            name='reg_coord',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowregcoord'),
        ),
        migrations.AlterField(
            model_name='nowregcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowregcoordpeople',
            name='reg_coord',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowregcoord'),
        ),
        migrations.AlterField(
            model_name='nowsedimentarystructure',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowspcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspcoordpeople',
            name='sp_coord',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AlterField(
            model_name='nowspcoordtaxa',
            name='sp_coord',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='sau_authorizer',
            field=models.ForeignKey(db_column='sau_authorizer', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='sau_coordinator',
            field=models.ForeignKey(db_column='sau_coordinator', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='species',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='suid',
            field=models.ForeignKey(db_column='suid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowspeciesupdate'),
        ),
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='strat_coord',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowstratcoord'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='low_bnd',
            field=models.ForeignKey(db_column='low_bnd', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_low_bnd', to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='sequence',
            field=models.ForeignKey(db_column='sequence', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowtimeunitsequence'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='up_bnd',
            field=models.ForeignKey(db_column='up_bnd', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_up_bnd', to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='bid',
            field=models.ForeignKey(db_column='bid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bau_authorizer',
            field=models.ForeignKey(db_column='bau_authorizer', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bau_coordinator',
            field=models.ForeignKey(db_column='bau_coordinator', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bid',
            field=models.ForeignKey(db_column='bid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='buid',
            field=models.ForeignKey(db_column='buid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tau_authorizer',
            field=models.ForeignKey(db_column='tau_authorizer', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tau_coordinator',
            field=models.ForeignKey(db_column='tau_coordinator', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='tuid',
            field=models.ForeignKey(db_column='tuid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='lower_buid',
            field=models.ForeignKey(blank=True, db_column='lower_buid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lower_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tuid',
            field=models.ForeignKey(blank=True, db_column='tuid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='upper_buid',
            field=models.ForeignKey(blank=True, db_column='upper_buid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_upper_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='refauthors',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='reffieldname',
            name='ref_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreferencetype'),
        ),
        migrations.AlterField(
            model_name='refkeywordsref',
            name='keywords',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refkeywords'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='journal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refjournal'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='ref_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreferencetype'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lid',
            field=models.ForeignKey(db_column='lid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='refkeywordsref',
            name='rid',
            field=models.ForeignKey(db_column='rid', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),

        ########################################
        # Fix ComMuseumList primary key
        ########################################
        migrations.AlterField(
            model_name='commuseumlist',
            name='museum',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='commuseumlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.RunSQL(fk_migration('now_mus', 'museum', 'com_mlist', 'museum')),

        ########################################
        # Fix ComPeople primary key
        ########################################
        migrations.AlterField(
            model_name='compeople',
            name='initials',
            field=models.CharField(max_length=10),
        ),

        migrations.AddField(
            model_name='compeople',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.RunSQL(fk_migration('now_bau', 'bau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_bau', 'bau_authorizer', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_lau', 'lau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_lau', 'lau_authorizer', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_proj', 'contact', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_proj_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_reg_coord_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_sau', 'sau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_sau', 'sau_authorizer', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_sp_coord_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_strat_coord_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_tau', 'tau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_tau', 'tau_authorizer', 'com_people', 'initials')),

        ########################################
        # Fix NowTimeUnitSequence primary key
        ########################################
        migrations.AlterField(
            model_name='nowtimeunitsequence',
            name='sequence',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='nowtimeunitsequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.RunSQL(fk_migration('now_time_unit', 'sequence', 'now_tu_sequence', 'sequence')),
        
        ########################################   
        # Fix NowTimeUnit primary key
        ########################################
        migrations.AlterField(
            model_name='nowtimeunit',
            name='tu_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='nowtimeunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        
        migrations.RunSQL(fk_migration('now_loc', 'bfa_max', 'now_time_unit', 'tu_name')),
        migrations.RunSQL(fk_migration('now_loc', 'bfa_min', 'now_time_unit', 'tu_name')),

        migrations.RunSQL(fk_migration('now_tau', 'tu_name', 'now_time_unit', 'tu_name')),

        migrations.RunSQL(fk_migration('now_time_update', 'tu_name', 'now_time_unit', 'tu_name')),

        ########################################
        # Recreate all constraints
        ########################################

        migrations.AlterField(
            model_name='nowcollectingmethod',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocality',
            name='bfa_max',
            field=models.ForeignKey(blank=True, db_column='bfa_max', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bfa_max', to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowlocality',
            name='bfa_min',
            field=models.ForeignKey(blank=True, db_column='bfa_min', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bfa_min', to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowlocalitysynonym',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lau_authorizer',
            field=models.ForeignKey(db_column='lau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lau_coordinator',
            field=models.ForeignKey(db_column='lau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='luid',
            field=models.ForeignKey(db_column='luid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocalityupdate'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowmuseum',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowmuseum',
            name='museum',
            field=models.ForeignKey(db_column='museum', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.commuseumlist'),
        ),
        migrations.AlterField(
            model_name='nowproject',
            name='contact',
            field=models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowprojectlocality',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowprojectlocality',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectspecies',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowregcoordcountry',
            name='reg_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowregcoord'),
        ),
        migrations.AlterField(
            model_name='nowregcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowregcoordpeople',
            name='reg_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowregcoord'),
        ),
        migrations.AlterField(
            model_name='nowsedimentarystructure',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowspcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspcoordpeople',
            name='sp_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AlterField(
            model_name='nowspcoordtaxa',
            name='sp_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='sau_authorizer',
            field=models.ForeignKey(db_column='sau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='sau_coordinator',
            field=models.ForeignKey(db_column='sau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='suid',
            field=models.ForeignKey(db_column='suid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowspeciesupdate'),
        ),
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='strat_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowstratcoord'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='low_bnd',
            field=models.ForeignKey(db_column='low_bnd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_low_bnd', to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='sequence',
            field=models.ForeignKey(db_column='sequence', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowtimeunitsequence'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='up_bnd',
            field=models.ForeignKey(db_column='up_bnd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_up_bnd', to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bau_authorizer',
            field=models.ForeignKey(db_column='bau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bau_coordinator',
            field=models.ForeignKey(db_column='bau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='buid',
            field=models.ForeignKey(db_column='buid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tau_authorizer',
            field=models.ForeignKey(db_column='tau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tau_coordinator',
            field=models.ForeignKey(db_column='tau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='tuid',
            field=models.ForeignKey(db_column='tuid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='lower_buid',
            field=models.ForeignKey(blank=True, db_column='lower_buid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lower_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tuid',
            field=models.ForeignKey(blank=True, db_column='tuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='upper_buid',
            field=models.ForeignKey(blank=True, db_column='upper_buid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_upper_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='refauthors',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='reffieldname',
            name='ref_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreferencetype'),
        ),
        migrations.AlterField(
            model_name='refkeywordsref',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refkeywords'),
        ),
        migrations.AlterField(
            model_name='refkeywordsref',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refjournal'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='ref_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreferencetype'),
        ),
        migrations.AlterUniqueTogether(
            name='nowcollectingmethod',
            unique_together={('lid', 'coll_meth')},
        ),
        migrations.AlterUniqueTogether(
            name='nowlocalityspecies',
            unique_together={('lid', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='nowlocalityupdatereference',
            unique_together={('luid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowmuseum',
            unique_together={('lid', 'museum')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectlocality',
            unique_together={('lid', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectpeople',
            unique_together={('pid', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectspecies',
            unique_together={('pid', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordcountry',
            unique_together={('reg_coord', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordpeople',
            unique_together={('reg_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowsedimentarystructure',
            unique_together={('lid', 'sed_struct')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordpeople',
            unique_together={('sp_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordtaxa',
            unique_together={('sp_coord', 'order_name', 'family_name')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspeciesupdatereference',
            unique_together={('suid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowstratcoordpeople',
            unique_together={('strat_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitboundaryreference',
            unique_together={('bid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitboundaryupdatereference',
            unique_together={('buid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitupdatereference',
            unique_together={('tuid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='refauthors',
            unique_together={('rid', 'field_id', 'au_num')},
        ),
        migrations.AlterUniqueTogether(
            name='reffieldname',
            unique_together={('field_id', 'ref_type')},
        ),
        migrations.AlterUniqueTogether(
            name='refkeywordsref',
            unique_together={('keywords', 'rid')},
        ),
    ]
