# Generated by Django 4.0.7 on 2022-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0005_replace_string_pk_with_numeric_pk_and_fix_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfamilysynonym',
            name='syn_family_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comgenussynonym',
            name='syn_genus_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comordersynonym',
            name='syn_order_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comsubfamilysynonym',
            name='syn_subfamily_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nowcollectingmethodvalue',
            name='coll_meth_value',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='nowregionalculture',
            name='regional_culture_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nowsedimentarystructurevalue',
            name='ss_value',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='comfamilysynonym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comgenussynonym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comordersynonym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comsubfamilysynonym',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nowcollectingmethodvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nowregionalculture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nowsedimentarystructurevalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        
    ]
