# Generated by Django 4.0.7 on 2022-10-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0005_rename_nowbau_nowtimeunitboundaryupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefRefType',
            new_name='RefReferenceType',
        ),
    ]
