# Generated by Django 4.0.7 on 2022-11-09 11:27

from django.db import migrations, models
import hashlib

def fk_migration(table, fk_column, foreign_table, pk_column):
    # 1. Create temporary column
    # 2. insert foreign table id to temp column by matching fk value to former pk column value
    # 3. replace original foreign key column with the temporary column and drop the original

    temp_col = fk_column + '_' + hashlib.md5(fk_column.encode('utf8')).hexdigest()

    return '''
        ALTER TABLE `{table}` ADD {temp_col} BIGINT (20);
        UPDATE `{table}` SET {temp_col} = (SELECT id FROM {foreign_table} WHERE {foreign_table}.{pk_column} = {table}.{fk_column});
        ALTER TABLE `{table}` DROP COLUMN {fk_column};
        ALTER TABLE `{table}` RENAME COLUMN {temp_col} TO {fk_column};
        '''.format(table=table, fk_column=fk_column, foreign_table=foreign_table, pk_column=pk_column, temp_col=temp_col)

class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0005_drop_unique_and_fk_constraints'),
    ]

    operations = [
        ########################################
        # Fix ComMuseumList primary key
        ########################################
        migrations.AlterField(
            model_name='commuseumlist',
            name='museum',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='commuseumlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.RunSQL(fk_migration('now_mus', 'museum', 'com_mlist', 'museum')),

        ########################################
        # Fix ComPeople primary key
        ########################################
        migrations.AlterField(
            model_name='compeople',
            name='initials',
            field=models.CharField(max_length=10),
        ),

        migrations.AddField(
            model_name='compeople',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.RunSQL(fk_migration('now_bau', 'bau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_bau', 'bau_authorizer', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_lau', 'lau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_lau', 'lau_authorizer', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_proj', 'contact', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_proj_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_reg_coord_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_sau', 'sau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_sau', 'sau_authorizer', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_sp_coord_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_strat_coord_people', 'initials', 'com_people', 'initials')),

        migrations.RunSQL(fk_migration('now_tau', 'tau_coordinator', 'com_people', 'initials')),
        migrations.RunSQL(fk_migration('now_tau', 'tau_authorizer', 'com_people', 'initials')),

        ########################################
        # Fix NowTimeUnitSequence primary key
        ########################################
        migrations.AlterField(
            model_name='nowtimeunitsequence',
            name='sequence',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='nowtimeunitsequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.RunSQL(fk_migration('now_time_unit', 'sequence', 'now_tu_sequence', 'sequence')),
        
        ########################################   
        # Fix NowTimeUnit primary key
        ########################################
        migrations.AlterField(
            model_name='nowtimeunit',
            name='tu_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='nowtimeunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        
        migrations.RunSQL(fk_migration('now_loc', 'bfa_max', 'now_time_unit', 'tu_name')),
        migrations.RunSQL(fk_migration('now_loc', 'bfa_min', 'now_time_unit', 'tu_name')),

        migrations.RunSQL(fk_migration('now_tau', 'tu_name', 'now_time_unit', 'tu_name')),

        migrations.RunSQL(fk_migration('now_time_update', 'tu_name', 'now_time_unit', 'tu_name')),
    ]
