# Generated by Django 4.0.7 on 2022-10-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0006_rename_refreftype_refreferencetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefRef',
            new_name='RefReference',
        ),
    ]
