# Generated by Django 4.0.7 on 2022-11-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0006_map_char_fk_to_int_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowcollectingmethod',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocality',
            name='bfa_max',
            field=models.ForeignKey(blank=True, db_column='bfa_max', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bfa_max', to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowlocality',
            name='bfa_min',
            field=models.ForeignKey(blank=True, db_column='bfa_min', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bfa_min', to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowlocalitysynonym',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lau_authorizer',
            field=models.ForeignKey(db_column='lau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lau_coordinator',
            field=models.ForeignKey(db_column='lau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdate',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='luid',
            field=models.ForeignKey(db_column='luid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocalityupdate'),
        ),
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowmuseum',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowmuseum',
            name='museum',
            field=models.ForeignKey(db_column='museum', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.commuseumlist'),
        ),
        migrations.AlterField(
            model_name='nowproject',
            name='contact',
            field=models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowprojectlocality',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowprojectlocality',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectspecies',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AlterField(
            model_name='nowprojectspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowregcoordcountry',
            name='reg_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowregcoord'),
        ),
        migrations.AlterField(
            model_name='nowregcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowregcoordpeople',
            name='reg_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowregcoord'),
        ),
        migrations.AlterField(
            model_name='nowsedimentarystructure',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowspcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspcoordpeople',
            name='sp_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AlterField(
            model_name='nowspcoordtaxa',
            name='sp_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='sau_authorizer',
            field=models.ForeignKey(db_column='sau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='sau_coordinator',
            field=models.ForeignKey(db_column='sau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_sau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='suid',
            field=models.ForeignKey(db_column='suid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowspeciesupdate'),
        ),
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='initials',
            field=models.ForeignKey(db_column='initials', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='strat_coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowstratcoord'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='low_bnd',
            field=models.ForeignKey(db_column='low_bnd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_low_bnd', to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='sequence',
            field=models.ForeignKey(db_column='sequence', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowtimeunitsequence'),
        ),
        migrations.AlterField(
            model_name='nowtimeunit',
            name='up_bnd',
            field=models.ForeignKey(db_column='up_bnd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_up_bnd', to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bau_authorizer',
            field=models.ForeignKey(db_column='bau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bau_coordinator',
            field=models.ForeignKey(db_column='bau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_bau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='buid',
            field=models.ForeignKey(db_column='buid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tau_authorizer',
            field=models.ForeignKey(db_column='tau_authorizer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tau_authorizer', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tau_coordinator',
            field=models.ForeignKey(db_column='tau_coordinator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tau_coordinator', to='now_app.compeople'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='tuid',
            field=models.ForeignKey(db_column='tuid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='lower_buid',
            field=models.ForeignKey(blank=True, db_column='lower_buid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lower_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tuid',
            field=models.ForeignKey(blank=True, db_column='tuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='upper_buid',
            field=models.ForeignKey(blank=True, db_column='upper_buid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_upper_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='refauthors',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='reffieldname',
            name='ref_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreferencetype'),
        ),
        migrations.AlterField(
            model_name='refkeywordsref',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refkeywords'),
        ),
        migrations.AlterField(
            model_name='refkeywordsref',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refjournal'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='ref_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreferencetype'),
        ),
        migrations.AlterUniqueTogether(
            name='nowcollectingmethod',
            unique_together={('lid', 'coll_meth')},
        ),
        migrations.AlterUniqueTogether(
            name='nowlocalityspecies',
            unique_together={('lid', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='nowlocalityupdatereference',
            unique_together={('luid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowmuseum',
            unique_together={('lid', 'museum')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectlocality',
            unique_together={('lid', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectpeople',
            unique_together={('pid', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowprojectspecies',
            unique_together={('pid', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordcountry',
            unique_together={('reg_coord', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='nowregcoordpeople',
            unique_together={('reg_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowsedimentarystructure',
            unique_together={('lid', 'sed_struct')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordpeople',
            unique_together={('sp_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspcoordtaxa',
            unique_together={('sp_coord', 'order_name', 'family_name')},
        ),
        migrations.AlterUniqueTogether(
            name='nowspeciesupdatereference',
            unique_together={('suid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowstratcoordpeople',
            unique_together={('strat_coord', 'initials')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitboundaryreference',
            unique_together={('bid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitboundaryupdatereference',
            unique_together={('buid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='nowtimeunitupdatereference',
            unique_together={('tuid', 'rid')},
        ),
        migrations.AlterUniqueTogether(
            name='refauthors',
            unique_together={('rid', 'field_id', 'au_num')},
        ),
        migrations.AlterUniqueTogether(
            name='reffieldname',
            unique_together={('field_id', 'ref_type')},
        ),
        migrations.AlterUniqueTogether(
            name='refkeywordsref',
            unique_together={('keywords', 'rid')},
        ),
    ]
