# Generated by Django 4.0.7 on 2022-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0007_alter_commain_one_alter_comspecies_species_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='lower_buid',
            field=models.BigIntegerField(blank=True, db_column='lower_buid', null=True),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tuid',
            field=models.BigIntegerField(blank=True, db_column='tuid', null=True),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='upper_buid',
            field=models.BigIntegerField(blank=True, db_column='upper_buid', null=True),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='journal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
