# Generated by Django 4.0.7 on 2022-10-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0007_rename_refref_refreference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowBr',
            new_name='NowTimeUnitBoundaryUpdateReference',
        ),
    ]
