# Generated by Django 4.0.7 on 2022-10-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0009_rename_nowcollmethvalues_nowcollectingmethodvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowLoc',
            new_name='NowLocality',
        ),
    ]
