# Generated by Django 4.1.7 on 2023-03-31 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0010_alter_nowtimeupdate_lower_buid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compeople',
            name='reg_coord',
            field=models.ManyToManyField(through='now_app.NowRegCoordPeople', to='now_app.nowregcoord'),
        ),
        migrations.AddField(
            model_name='compeople',
            name='sp_coord',
            field=models.ManyToManyField(through='now_app.NowSpCoordPeople', to='now_app.nowspcoord'),
        ),
        migrations.AddField(
            model_name='compeople',
            name='strat_coord',
            field=models.ManyToManyField(through='now_app.NowStratCoordPeople', to='now_app.nowstratcoord'),
        ),
        migrations.AddField(
            model_name='nowlocality',
            name='museum',
            field=models.ManyToManyField(through='now_app.NowMuseum', to='now_app.commuseumlist'),
        ),
        migrations.AddField(
            model_name='nowlocality',
            name='species',
            field=models.ManyToManyField(through='now_app.NowLocalitySpecies', to='now_app.comspecies'),
        ),
        migrations.AddField(
            model_name='nowlocalityupdate',
            name='reference',
            field=models.ManyToManyField(through='now_app.NowLocalityUpdateReference', to='now_app.refreference'),
        ),
        migrations.AddField(
            model_name='nowproject',
            name='localities',
            field=models.ManyToManyField(through='now_app.NowProjectLocality', to='now_app.nowlocality'),
        ),
        migrations.AddField(
            model_name='nowproject',
            name='people',
            field=models.ManyToManyField(through='now_app.NowProjectPeople', to='now_app.compeople'),
        ),
        migrations.AddField(
            model_name='nowproject',
            name='species',
            field=models.ManyToManyField(through='now_app.NowProjectSpecies', to='now_app.comspecies'),
        ),
        migrations.AddField(
            model_name='nowspeciesupdate',
            name='references',
            field=models.ManyToManyField(through='now_app.NowSpeciesUpdateReference', to='now_app.refreference'),
        ),
        migrations.AddField(
            model_name='nowtimeunitboundary',
            name='references',
            field=models.ManyToManyField(through='now_app.NowTimeUnitBoundaryReference', to='now_app.refreference'),
        ),
        migrations.AddField(
            model_name='nowtimeunitboundaryupdate',
            name='references',
            field=models.ManyToManyField(through='now_app.NowTimeUnitBoundaryUpdateReference', to='now_app.refreference'),
        ),
        migrations.AddField(
            model_name='nowtimeunitupdate',
            name='references',
            field=models.ManyToManyField(through='now_app.NowTimeUnitUpdateReference', to='now_app.refreference'),
        ),
        migrations.AddField(
            model_name='refreference',
            name='keywords',
            field=models.ManyToManyField(through='now_app.RefKeywordsRef', to='now_app.refkeywords'),
        ),
        migrations.AlterField(
            model_name='nowproject',
            name='contact',
            field=models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_contact', to='now_app.compeople'),
        ),
    ]
