# Generated by Django 4.1.7 on 2023-06-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0011_compeople_reg_coord_compeople_sp_coord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_references', to='now_app.refjournal'),
        ),
    ]
