# Generated by Django 4.0.7 on 2022-10-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0011_rename_nowcollmeth_nowcollectingmethod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowLau',
            new_name='NowLocalityUpdate',
        ),
    ]
