# Generated by Django 4.1.7 on 2023-06-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0012_alter_refreference_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comspecies',
            name='locomo1',
            field=models.CharField(blank=True, choices=[('ae', 'Aerial'), ('aq', 'Aquatic'), ('sa', 'Semi-Aquatic'), ('te', 'Terrestrial')], default='', help_text='The most general substrate of locomotion.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comspecies',
            name='locomo2',
            field=models.CharField(blank=True, choices=[('aerial', 'aerial'), ('arboreal', 'arboreal'), ('fossorial', 'fossorial'), ('npow_flight', 'non-powered flight'), ('pow_flight', 'powered flight'), ('scansorial', 'scansorial'), ('semi-fossorial', 'semi-fossorial'), ('surficial', 'surficial'), ('swimming', 'swimming')], default='', help_text='Specific substrate of terrestrial locomotion, or type of flying.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comspecies',
            name='locomo3',
            field=models.CharField(blank=True, choices=[('arboreal', 'Arboreal'), ('arb_above_br', 'arboreal, above-branch'), ('arb_suspensory', 'arboreal, below-branch suspensory'), ('bipedal_str', 'bipedal striding'), ('cursorial', 'cursorial:running specialists'), ('fast_flight', 'fast powered flight'), ('gen_quad', 'general, unspecialized quadrupedal'), ('glide', 'short, controlled nonpowered flight, glide angle < 45deg.'), ('graviportal', 'graviportal'), ('hover', 'powered flightwith specializations for hovering'), ('k_walk', 'knuckle-walking'), ('parachute', 'nonpowered flight, glide angle > 45deg.'), ('saltatory', 'jumping, hopping, ricochetal'), ('s/f_flight', 'fly slow or fast'), ('slow_flight', 'slow powered flight'), ('soar', 'all types of soaring'), ('undulate', 'undulate'), ('sub_curs', 'sub cursorial'), ('hyper_curs', 'hyper cursorial'), ('swim_parax', 'swim parax')], default='', help_text='Specific substrate of terrestrial locomotion, or type of flying.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='now_locality_species', to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='now_locality_species', to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='refauthors',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors', to='now_app.refreference'),
        ),
        migrations.AlterField(
            model_name='refreference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refjournal'),
        ),
    ]
