# Generated by Django 4.1.7 on 2023-06-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0013_alter_comspecies_locomo1_alter_comspecies_locomo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='lid',
            field=models.ForeignKey(db_column='lid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='locality_species', to='now_app.nowlocality'),
        ),
        migrations.AlterField(
            model_name='nowlocalityspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='species_locality', to='now_app.comspecies'),
        ),
        migrations.AlterField(
            model_name='nowspeciesupdate',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='species_update', to='now_app.comspecies'),
        ),
    ]
