# Generated by Django 4.0.7 on 2022-10-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0013_rename_nowlr_nowlocalityupdatereference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowLs',
            new_name='NowLocalitySpecies',
        ),
        migrations.RenameModel(
            old_name='NowLsCopy',
            new_name='NowLocalitySpeciesCopy',
        ),
    ]
