# Generated by Django 4.0.7 on 2022-10-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0014_rename_nowls_nowlocalityspecies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowMus',
            new_name='NowMuseum',
        ),
    ]
