# Generated by Django 4.0.7 on 2022-10-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0015_rename_nowmus_nowmuseum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowProj',
            new_name='NowProject',
        ),
    ]
