# Generated by Django 4.0.7 on 2022-10-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0019_rename_nowpsr_nowprojectspecies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowSau',
            new_name='NowSpeciesUpdate',
        ),
    ]
