# Generated by Django 4.0.7 on 2022-10-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0020_rename_nowsau_nowspeciesupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowSr',
            new_name='NowSpeciesUpdateReference',
        ),
    ]
