# Generated by Django 4.0.7 on 2022-10-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0021_rename_nowsr_nowspeciesupdatereference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowSs',
            new_name='NowSedimentaryStructure',
        ),
        migrations.RenameModel(
            old_name='NowSsValues',
            new_name='NowSedimentaryStructureValue',
        ),
    ]
