# Generated by Django 4.0.7 on 2022-10-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0025_rename_nowtr_nowtimeunitupdatereference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NowTur',
            new_name='NowTimeUnitBoundaryReference',
        ),
    ]
