# Generated by Django 4.0.7 on 2022-10-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0027_rename_refkeywordsref_refkeywordsreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comtaxasynonym',
            name='species_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.comspecies'),
        ),
    ]
