# Generated by Django 4.0.7 on 2022-10-31 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0028_alter_comtaxasynonym_species_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdate',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
    ]
