# Generated by Django 4.0.7 on 2022-10-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0030_nowtimeunitboundaryupdatereference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeunitboundaryupdatereference',
            name='buid',
            field=models.OneToOneField(db_column='buid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundaryupdate'),
        ),
    ]
