# Generated by Django 4.0.7 on 2022-10-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0035_nowlocalityupdatereference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowlocalityupdatereference',
            name='luid',
            field=models.OneToOneField(db_column='luid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowlocalityupdate'),
        ),
    ]
