# Generated by Django 4.0.7 on 2022-10-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0041_alter_nowprojectlocality_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowprojectpeople',
            name='pid',
            field=models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowproject'),
        ),
        migrations.AddField(
            model_name='nowprojectpeople',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
