# Generated by Django 4.0.7 on 2022-10-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0046_nowspcoordpeople_id_alter_nowspcoordpeople_sp_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowspcoordtaxa',
            name='sp_coord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspcoord'),
        ),
        migrations.AddField(
            model_name='nowspcoordtaxa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
