# Generated by Django 4.0.7 on 2022-10-31 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0047_nowspcoordtaxa_id_alter_nowspcoordtaxa_sp_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='suid',
            field=models.OneToOneField(db_column='suid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowspeciesupdate'),
        ),
        migrations.AddField(
            model_name='nowspeciesupdatereference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
