# Generated by Django 4.0.7 on 2022-10-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0048_nowspeciesupdatereference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowspeciesupdatereference',
            name='suid',
            field=models.OneToOneField(db_column='suid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowspeciesupdate'),
        ),
    ]
