# Generated by Django 4.0.7 on 2022-10-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0049_alter_nowspeciesupdatereference_suid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowsedimentarystructure',
            name='lid',
            field=models.OneToOneField(db_column='lid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowlocality'),
        ),
        migrations.AddField(
            model_name='nowsedimentarystructure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
