# Generated by Django 4.0.7 on 2022-10-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0051_alter_nowsedimentarystructure_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowstratcoordpeople',
            name='strat_coord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowstratcoord'),
        ),
        migrations.AddField(
            model_name='nowstratcoordpeople',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
