# Generated by Django 4.0.7 on 2022-10-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0053_alter_nowlocalitysynonym_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeunitupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
    ]
