# Generated by Django 4.0.7 on 2022-10-31 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0054_alter_nowtimeunitupdate_tu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='lower_buid',
            field=models.ForeignKey(blank=True, db_column='lower_buid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_lower_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tu_name',
            field=models.ForeignKey(db_column='tu_name', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunit'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='tuid',
            field=models.ForeignKey(blank=True, db_column='tuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AlterField(
            model_name='nowtimeupdate',
            name='upper_buid',
            field=models.ForeignKey(blank=True, db_column='upper_buid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_upper_buid', to='now_app.nowtimeunitboundaryupdate'),
        ),
    ]
