# Generated by Django 4.0.7 on 2022-10-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0055_alter_nowtimeupdate_lower_buid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeunitupdatereference',
            name='tuid',
            field=models.OneToOneField(db_column='tuid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowtimeunitupdate'),
        ),
        migrations.AddField(
            model_name='nowtimeunitupdatereference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
