# Generated by Django 4.0.7 on 2022-10-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0056_nowtimeunitupdatereference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='bid',
            field=models.OneToOneField(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.nowtimeunitboundary'),
        ),
        migrations.AddField(
            model_name='nowtimeunitboundaryreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
