# Generated by Django 4.0.7 on 2022-10-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0058_alter_nowtimeunitupdatereference_tuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowtimeunitboundaryreference',
            name='bid',
            field=models.OneToOneField(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='now_app.nowtimeunitboundary'),
        ),
    ]
