# Generated by Django 4.0.7 on 2022-10-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0059_alter_nowtimeunitboundaryreference_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refauthors',
            name='rid',
            field=models.OneToOneField(db_column='rid', on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refreference'),
        ),
        migrations.AddField(
            model_name='refauthors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
