# Generated by Django 4.0.7 on 2022-10-31 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0061_reffieldname_id_alter_reffieldname_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refkeywordsreference',
            name='keywords',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='now_app.refkeywords'),
        ),
        migrations.AddField(
            model_name='refkeywordsreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
