# Generated by Django 4.0.7 on 2022-10-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now_app', '0062_refkeywordsreference_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comtaxasynonym',
            old_name='species_id',
            new_name='species',
        ),
    ]
